### ISSUE TITLE
New REST API version

### ISSUE THREAD

**Issue by gustavooferreira** [oanda/oandapy#30]
Hey guys, OANDA is moving towards **REST-V20.**

Although it is not fully implemented, new accounts can only communicate with the new version, so it would be nice if you guys could upgrade the code.
I would really appreciate it.
I didn't went through all the documentation, but it seems it is just a matter of changing the endpoint address.

**Comment by gustavooferreira** [comment]
Now that I am reading the API more carefully, it actually changed a great deal.

Maybe, it is better to create another module/class, or create another project, to separate the two of them?

**Comment by ronensinger** [comment]
I agree,

**Comment by RadiusVector** [comment]
+1, this would be greatly appreciated.

**Comment by hootnot** [comment]
I've read the docs partially. It'is still under development for some components (streaming / history / forex labs).  I will take a closer look at the docs.

**Comment by gustavooferreira** [comment]
Hey guys,
I am developing a wrapper for the REST-v20 API.
It is still in its testing phase, I think I need a couple more days to make sure that everything is working as it should, and then I will make its first release.

Feel free to use it, contribute or fork it to go in a different path.

**Comment by hootnot** [comment]
Hi everyone,

My development for the REST-V20 API: https://github.com/hootnot/oanda-api-v20
