### ISSUE TITLE
Publish OANDAPY on https://pypi.python.org/pypi

### ISSUE THREAD

**Issue by davidandreoletti** [oanda/oandapy#39]
It would be nice to have oandapy available on https://pypi.python.org/pypi for the following reasons:
- 3rd party libraries can rely on it
- Increases oandapy as the defacto library for python enabled OANDA REST

Is this something you would like to do in the near future ?

**Comment by hootnot** [comment]
OANDA has released the REST-V20 API. This new REST-API offers  a lot more then the current API .

Check https://github.com/hootnot/oanda-api-v20. A pypi package will be released soon.

**Comment by davidandreoletti** [comment]
@hootnot Sweet! I will have a look at REST v20

**Comment by davidandreoletti** [comment]
@hootnot Are https://github.com/hootnot/oanda-api-v20 and https://github.com/oanda/v20-python related ?

**Comment by hootnot** [comment]
@davidandreoletti  ... no oanda-api-v20 and v20-python are **not** related. v20-python seems to be autogenerated. I wrote oanda-api-v20 from the specs on developer.oanda.com. I am waiting for the missing forexlabs endpoint. Some higher level abstraction classes will be added also.

**Comment by davidandreoletti** [comment]
@hootnot Ok. FYI: https://github.com/hootnot/oanda-api-v20 is now used to retrieve Instruments one of the new panda-datareaders (https://github.com/pydata/pandas-datareader/pull/257)

Thanks for your OSS contribution!

**Comment by hootnot** [comment]
@davidandreoletti 

Today I've released the pypi-package of my Python REST-V20 wrapper.

Simple test scenario (on linux):

``` shell
~user % virtualenv oanda
~user % . ./oanda/bin/activate
~user %  pip install oandapyV20

Collecting oandapyV20
  Downloading oandapyV20-0.2.1.tar.gz
Collecting requests>=2.10 (from oandapyV20)
  Using cached requests-2.12.0-py2.py3-none-any.whl
Collecting six>=1.10 (from oandapyV20)
  Using cached six-1.10.0-py2.py3-none-any.whl
Building wheels for collected packages: oandapyV20
  Running setup.py bdist_wheel for oandapyV20 ... done
  Stored in directory: /home/hootnot/.cache/pip/wheels/b0/eb/9d/65ae9ff2c445840937a014959f3ddfe230887d627729f75e79
Successfully built oandapyV20
Installing collected packages: requests, six, oandapyV20
Successfully installed oandapyV20-0.2.1 requests-2.12.0 six-1.10.0
```

Install the examples from the git-repo:

``` bash
~user% git clone https://github.com/hootnot/oanda-api-v20
~user% cd oanda-api-v20/examples/
```

Edit _account.txt_  and _token.txt_ to run the examples:

``` bash
~user%  python streaming_prices.py --instruments EUR_USD,EUR_JPY
~user%  python candle-data.py  --nice --count 5 --gran M5 --instrum DE30_EUR,EUR_USD
~user%  python neworder.py
~user%  python contrib_mo_tp_sl.py
```
